<a href="https://colab.research.google.com/github/gomesrocha/DataVectorization/blob/main/pratica_chromadb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prática com ChromaDB - Notebook Colab

## Material Prático Complementar

Este notebook demonstra na prática como usar o ChromaDB com o modelo de embedding padrão (all-MiniLM-L6-v2), sem qualquer dependência externa.

**Requisitos:**
- Apenas `chromadb` (já inclui tudo o que precisamos)
- Sem necessidade de chaves de API
- Funciona completamente offline

## 1. Instalação e Verificação

In [ ]:
# Instalar ChromaDB
!pip install chromadb -q

# Verificar instalação
import chromadb
print(f"ChromaDB versão: {chromadb.__version__}")
print("✓ ChromaDB instalado com sucesso!")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 57.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 48.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 44.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.9/178.9 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.3.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.43.0 which is incompatible.
google-adk 2.3.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.43.0 which is incompatible.
ChromaDB versão: 1.5.9
✓ ChromaDB instalado com sucesso!

## 2. Inicializando o Cliente e Criando uma Coleção

In [ ]:
# Criar cliente em memória (ideal para testes)
client = chromadb.Client()

# Criar uma coleção
collection = client.create_collection(
    name="base_conhecimento",
    metadata={"descricao": "Base de conhecimento sobre tecnologia"}
)

print(f"✓ Coleção '{collection.name}' criada com sucesso!")
print(f"  Metadados: {collection.metadata}")

✓ Coleção 'base_conhecimento' criada com sucesso!
  Metadados: {'descricao': 'Base de conhecimento sobre tecnologia'}

## 3. Adicionando Dados (CREATE)

Vamos adicionar documentos sobre diferentes tópicos de tecnologia.

In [ ]:
# Preparar dados
documentos = [
    "ChromaDB é um banco de dados vetorial open-source focado em IA e aplicações de busca semântica.",
    "Python é uma linguagem de programação versátil usada em data science, web e automação.",
    "Bancos de dados relacionais usam SQL e armazenam dados em tabelas com relacionamentos.",
    "Embeddings são representações numéricas de texto que capturam significado semântico em um espaço vetorial.",
    "O Google Colab permite executar código Python no navegador sem necessidade de instalação local.",
    "Machine Learning é um subcampo da IA que permite aos computadores aprender com dados.",
    "Vetores de alta dimensão são usados para representar dados complexos em espaços matemáticos.",
    "Busca semântica encontra documentos com significado similar, não apenas correspondências exatas.",
    "A distância euclidiana mede a proximidade entre dois pontos em um espaço vetorial.",
    "Sentence Transformers é uma biblioteca que gera embeddings de alta qualidade para frases e documentos."
]

metadados = [
    {"categoria": "banco_de_dados", "tipo": "vetorial", "ano": 2024},
    {"categoria": "programacao", "linguagem": "python", "ano": 2024},
    {"categoria": "banco_de_dados", "tipo": "relacional", "ano": 2024},
    {"categoria": "ia", "conceito": "embedding", "ano": 2024},
    {"categoria": "ferramenta", "ambiente": "nuvem", "ano": 2024},
    {"categoria": "ia", "conceito": "machine_learning", "ano": 2024},
    {"categoria": "matematica", "topico": "vetores", "ano": 2024},
    {"categoria": "busca", "tipo": "semantica", "ano": 2024},
    {"categoria": "matematica", "topico": "distancia", "ano": 2024},
    {"categoria": "ia", "conceito": "nlp", "ano": 2024}
]

ids = [f"doc_{i+1}" for i in range(len(documentos))]

# Adicionar à coleção
collection.add(
    documents=documentos,
    metadatas=metadados,
    ids=ids
)

print(f"✓ {collection.count()} documentos adicionados à coleção!")
print("\nPrimeiros 3 documentos:")
for i, doc in enumerate(documentos[:3]):
    print(f"  {i+1}. {doc[:70]}...")

/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: 100%|██████████| 79.3M/79.3M [00:01<00:00, 46.1MiB/s]

✓ 10 documentos adicionados à coleção!

Primeiros 3 documentos:
  1. ChromaDB é um banco de dados vetorial open-source focado em IA e aplic...
  2. Python é uma linguagem de programação versátil usada em data science, ...
  3. Bancos de dados relacionais usam SQL e armazenam dados em tabelas com ...

## 4. Recuperando Dados (READ)

In [ ]:
# Recuperar um documento específico
resultado = collection.get(ids=["doc_1"])

print("Documento recuperado:")
print(f"  ID: {resultado['ids'][0]}")
print(f"  Texto: {resultado['documents'][0]}")
print(f"  Metadados: {resultado['metadatas'][0]}")

# Recuperar com embeddings
resultado_com_embedding = collection.get(
    ids=["doc_1"],
    include=["embeddings"]
)

embedding = resultado_com_embedding['embeddings'][0]
print(f"\nDimensões do embedding: {len(embedding)}")
print(f"Primeiros 5 valores: {embedding[:5]}")

Documento recuperado:
  ID: doc_1
  Texto: ChromaDB é um banco de dados vetorial open-source focado em IA e aplicações de busca semântica.
  Metadados: {'tipo': 'vetorial', 'ano': 2024, 'categoria': 'banco_de_dados'}

Dimensões do embedding: 384
Primeiros 5 valores: [ 0.01412447 -0.01216339 -0.09484315 -0.06536509 -0.04640942]

## 5. Busca Semântica - O Coração do ChromaDB

In [ ]:
# Realizar uma busca semântica
pergunta = "Como representar textos com números?"

resultados = collection.query(
    query_texts=[pergunta],
    n_results=3
)

print(f"Pergunta: '{pergunta}'\n")
print("Top 3 documentos mais relevantes:")
print("-" * 80)

for i, (doc, distancia, metadata) in enumerate(zip(
    resultados['documents'][0],
    resultados['distances'][0],
    resultados['metadatas'][0]
)):
    print(f"\n{i+1}. Distância: {distancia:.4f}")
    print(f"   Categoria: {metadata['categoria']}")
    print(f"   Texto: {doc}")

Pergunta: 'Como representar textos com números?'

Top 3 documentos mais relevantes:
--------------------------------------------------------------------------------

1. Distância: 0.7509
   Categoria: ia
   Texto: Embeddings são representações numéricas de texto que capturam significado semântico em um espaço vetorial.

2. Distância: 0.9237
   Categoria: matematica
   Texto: Vetores de alta dimensão são usados para representar dados complexos em espaços matemáticos.

3. Distância: 1.1323
   Categoria: busca
   Texto: Busca semântica encontra documentos com significado similar, não apenas correspondências exatas.

## 6. Múltiplas Buscas Simultâneas

In [ ]:
# Fazer múltiplas buscas de uma vez
perguntas = [
    "O que é um banco de dados?",
    "Como funciona o Python?",
    "O que é inteligência artificial?"
]

resultados_multiplos = collection.query(
    query_texts=perguntas,
    n_results=2
)

for query_idx, pergunta in enumerate(perguntas):
    print(f"\n{'='*80}")
    print(f"Pergunta {query_idx+1}: '{pergunta}'")
    print(f"{'='*80}")

    for i, (doc, distancia) in enumerate(zip(
        resultados_multiplos['documents'][query_idx],
        resultados_multiplos['distances'][query_idx]
    )):
        print(f"\n  {i+1}. (Distância: {distancia:.4f})")
        print(f"     {doc[:70]}...")

================================================================================
Pergunta 1: 'O que é um banco de dados?'
================================================================================

  1. (Distância: 0.7385)
     Bancos de dados relacionais usam SQL e armazenam dados em tabelas com ...

  2. (Distância: 0.7794)
     Vetores de alta dimensão são usados para representar dados complexos e...

================================================================================
Pergunta 2: 'Como funciona o Python?'
================================================================================

  1. (Distância: 0.8059)
     O Google Colab permite executar código Python no navegador sem necessi...

  2. (Distância: 0.8191)
     Python é uma linguagem de programação versátil usada em data science, ...

================================================================================
Pergunta 3: 'O que é inteligência artificial?'
================================================================================

  1. (Distância: 1.0090)
     Vetores de alta dimensão são usados para representar dados complexos e...

  2. (Distância: 1.0387)
     Machine Learning é um subcampo da IA que permite aos computadores apre...

## 7. Filtragem por Metadados

In [ ]:
# Busca com filtro simples
pergunta = "Tecnologia e dados"

resultados_filtrados = collection.query(
    query_texts=[pergunta],
    n_results=5,
    where={"categoria": {"$eq": "ia"}}
)

print(f"Pergunta: '{pergunta}'")
print(f"Filtro: Apenas documentos da categoria 'ia'\n")
print("Resultados:")

for i, (doc, metadata) in enumerate(zip(
    resultados_filtrados['documents'][0],
    resultados_filtrados['metadatas'][0]
)):
    print(f"\n{i+1}. {doc}")
    print(f"   Categoria: {metadata['categoria']}, Conceito: {metadata.get('conceito', 'N/A')}")

Pergunta: 'Tecnologia e dados'
Filtro: Apenas documentos da categoria 'ia'

Resultados:

1. Machine Learning é um subcampo da IA que permite aos computadores aprender com dados.
   Categoria: ia, Conceito: machine_learning

2. Embeddings são representações numéricas de texto que capturam significado semântico em um espaço vetorial.
   Categoria: ia, Conceito: embedding

3. Sentence Transformers é uma biblioteca que gera embeddings de alta qualidade para frases e documentos.
   Categoria: ia, Conceito: nlp

## 8. Filtros Complexos com $and   e   $or

In [ ]:
# Filtro com $and (TODAS as condições devem ser verdadeiras)
print("FILTRO COM $AND (TODAS as condições)")
print("="*80)

resultados_and = collection.query(
    query_texts=["tecnologia"],
    n_results=10,
    where={
        "$and": [
            {"categoria": {"$eq": "ia"}},
            {"ano": {"$gte": 2024}}
        ]
    }
)

print(f"Documentos de categoria 'ia' E ano >= 2024:")
for i, doc in enumerate(resultados_and['documents'][0]):
    print(f"  {i+1}. {doc[:60]}...")

# Filtro com $or (QUALQUER UMA das condições pode ser verdadeira)
print(f"\n\nFILTRO COM $OR (QUALQUER UMA das condições)")
print("="*80)

resultados_or = collection.query(
    query_texts=["dados"],
    n_results=10,
    where={
        "$or": [
            {"categoria": "banco_de_dados"},
            {"categoria": "ia"}
        ]
    }
)

print(f"Documentos de categoria 'banco_de_dados' OU 'ia':")
for i, (doc, metadata) in enumerate(zip(
    resultados_or['documents'][0],
    resultados_or['metadatas'][0]
)):
    print(f"  {i+1}. [{metadata['categoria']}] {doc[:50]}...")

FILTRO COM $AND (TODAS as condições)
================================================================================
Documentos de categoria 'ia' E ano >= 2024:
  1. Embeddings são representações numéricas de texto que captura...
  2. Machine Learning é um subcampo da IA que permite aos computa...
  3. Sentence Transformers é uma biblioteca que gera embeddings d...


FILTRO COM $OR (QUALQUER UMA das condições)
================================================================================
Documentos de categoria 'banco_de_dados' OU 'ia':
  1. [banco_de_dados] Bancos de dados relacionais usam SQL e armazenam d...
  2. [ia] Machine Learning é um subcampo da IA que permite a...
  3. [banco_de_dados] ChromaDB é um banco de dados vetorial open-source ...
  4. [ia] Embeddings são representações numéricas de texto q...
  5. [ia] Sentence Transformers é uma biblioteca que gera em...

## 9. Atualizando Dados (UPDATE)

In [ ]:
# Antes da atualização
antes = collection.get(ids=["doc_2"])
print("ANTES DA ATUALIZAÇÃO:")
print(f"  Texto: {antes['documents'][0]}")
print(f"  Metadados: {antes['metadatas'][0]}")

# Atualizar o documento
collection.update(
    ids=["doc_2"],
    documents=["Python é uma linguagem de programação extremamente versátil, usada em IA, web, automação e análise de dados."],
    metadatas=[{"categoria": "programacao", "linguagem": "python", "ano": 2024, "atualizado": True}]
)

# Depois da atualização
depois = collection.get(ids=["doc_2"])
print("\nDEPOIS DA ATUALIZAÇÃO:")
print(f"  Texto: {depois['documents'][0]}")
print(f"  Metadados: {depois['metadatas'][0]}")

ANTES DA ATUALIZAÇÃO:
  Texto: Python é uma linguagem de programação versátil usada em data science, web e automação.
  Metadados: {'categoria': 'programacao', 'ano': 2024, 'linguagem': 'python'}

DEPOIS DA ATUALIZAÇÃO:
  Texto: Python é uma linguagem de programação extremamente versátil, usada em IA, web, automação e análise de dados.
  Metadados: {'atualizado': True, 'categoria': 'programacao', 'ano': 2024, 'linguagem': 'python'}

## 10. UPSERT - Adicionar ou Atualizar

In [ ]:
# UPSERT é útil quando você não sabe se o documento já existe

# Primeiro, vamos tentar adicionar um novo documento
collection.upsert(
    ids=["doc_11"],
    documents=["Novo documento adicionado via UPSERT"],
    metadatas=[{"categoria": "teste", "tipo": "novo"}]
)

print(f"Total de documentos após UPSERT: {collection.count()}")

# Agora vamos atualizar o mesmo documento
collection.upsert(
    ids=["doc_11"],
    documents=["Documento atualizado via UPSERT"],
    metadatas=[{"categoria": "teste", "tipo": "atualizado"}]
)

print(f"Total de documentos após segundo UPSERT: {collection.count()}")

# Verificar o resultado
resultado = collection.get(ids=["doc_11"])
print(f"\nDocumento final:")
print(f"  {resultado['documents'][0]}")
print(f"  Metadados: {resultado['metadatas'][0]}")

Total de documentos após UPSERT: 11
Total de documentos após segundo UPSERT: 11

Documento final:
  Documento atualizado via UPSERT
  Metadados: {'categoria': 'teste', 'tipo': 'atualizado'}

## 11. Deletando Dados (DELETE)

In [ ]:
print(f"Total de documentos ANTES da exclusão: {collection.count()}")

# Deletar um documento específico
collection.delete(ids=["doc_11"])

print(f"Total de documentos APÓS deletar doc_11: {collection.count()}")

# Deletar por filtro de metadados
# (Vamos deletar documentos cuja categoria começa com 'teste')
# Nota: Isso é apenas para demonstração

print("\n✓ Documento deletado com sucesso!")

Total de documentos ANTES da exclusão: 11
Total de documentos APÓS deletar doc_11: 10

✓ Documento deletado com sucesso!

## 12. Análise de Distâncias e Similaridade

In [ ]:
# Entender como as distâncias funcionam

# Busca 1: Pergunta muito relacionada
resultado1 = collection.query(
    query_texts=["Banco de dados vetorial para IA"],
    n_results=1
)

# Busca 2: Pergunta pouco relacionada
resultado2 = collection.query(
    query_texts=["Receita de bolo de chocolate"],
    n_results=1
)

distancia1 = resultado1['distances'][0][0]
distancia2 = resultado2['distances'][0][0]

print("ANÁLISE DE DISTÂNCIAS")
print("="*80)
print(f"\nPergunta 1: 'Banco de dados vetorial para IA'")
print(f"  Distância: {distancia1:.4f}")
print(f"  Documento: {resultado1['documents'][0][0][:60]}...")

print(f"\nPergunta 2: 'Receita de bolo de chocolate'")
print(f"  Distância: {distancia2:.4f}")
print(f"  Documento: {resultado2['documents'][0][0][:60]}...")

print(f"\n\nInterpretação:")
print(f"  - Distância menor ({distancia1:.4f}) = Mais similar")
print(f"  - Distância maior ({distancia2:.4f}) = Menos similar")
print(f"  - Diferença: {abs(distancia2 - distancia1):.4f}")

ANÁLISE DE DISTÂNCIAS
================================================================================

Pergunta 1: 'Banco de dados vetorial para IA'
  Distância: 0.8543
  Documento: Vetores de alta dimensão são usados para representar dados c...

Pergunta 2: 'Receita de bolo de chocolate'
  Distância: 1.2655
  Documento: A distância euclidiana mede a proximidade entre dois pontos ...


Interpretação:
  - Distância menor (0.8543) = Mais similar
  - Distância maior (1.2655) = Menos similar
  - Diferença: 0.4112

## 13. Persistência - Salvando Dados em Disco

In [ ]:
# Criar um cliente com persistência
client_persistente = chromadb.PersistentClient(path="./meu_banco_chroma")

# Criar uma coleção
collection_persistente = client_persistente.create_collection(
    name="dados_persistidos",
    metadata={"descricao": "Dados salvos em disco"}
)

# Adicionar dados
collection_persistente.add(
    ids=["persistido_1", "persistido_2"],
    documents=[
        "Este documento será salvo em disco",
        "Mesmo após fechar o notebook, os dados permanecerão"
    ]
)

print(f"✓ {collection_persistente.count()} documentos adicionados e persistidos")
print(f"  Localização: ./meu_banco_chroma")
print(f"\nOs dados agora estão salvos em disco e podem ser recuperados em futuras execuções!")

✓ 2 documentos adicionados e persistidos
  Localização: ./meu_banco_chroma

Os dados agora estão salvos em disco e podem ser recuperados em futuras execuções!

## 14. Gerenciando Múltiplas Coleções

In [ ]:
# Listar todas as coleções
colecoes = client.list_collections()
print(f"Coleções no cliente em memória: {len(colecoes)}")
for col in colecoes:
    print(f"  - {col.name} ({col.count()} documentos)")

# Obter uma coleção existente
col_existente = client.get_collection(name="base_conhecimento")
print(f"\nColeção obtida: {col_existente.name}")
print(f"Total de documentos: {col_existente.count()}")

# Obter ou criar (útil para evitar erros)
col_ou_criar = client.get_or_create_collection(name="base_conhecimento")
print(f"\nColeção (get_or_create): {col_ou_criar.name}")

Coleções no cliente em memória: 1
  - base_conhecimento (10 documentos)

Coleção obtida: base_conhecimento
Total de documentos: 10

Coleção (get_or_create): base_conhecimento

## 15. Exemplo Completo: Sistema de Busca de Documentos

In [ ]:
# Criar um sistema de busca simples

def buscar_documentos(colecao, pergunta, categoria=None, n_resultados=3):
    """
    Busca documentos na coleção.

    Args:
        colecao: Coleção do ChromaDB
        pergunta: Texto da pergunta
        categoria: Filtro opcional de categoria
        n_resultados: Número de resultados desejados

    Returns:
        Lista de resultados com documentos, distâncias e metadados
    """

    where_filter = None
    if categoria:
        where_filter = {"categoria": {"$eq": categoria}}

    resultados = colecao.query(
        query_texts=[pergunta],
        n_results=n_resultados,
        where=where_filter
    )

    return resultados

# Usar a função
print("SISTEMA DE BUSCA DE DOCUMENTOS")
print("="*80)

# Busca 1: Sem filtro
print("\n1. Busca geral por 'inteligência artificial'")
resultado = buscar_documentos(collection, "inteligência artificial", n_resultados=2)
for i, doc in enumerate(resultado['documents'][0]):
    print(f"   {i+1}. {doc[:70]}...")

# Busca 2: Com filtro de categoria
print("\n2. Busca por 'dados' apenas na categoria 'ia'")
resultado = buscar_documentos(collection, "dados", categoria="ia", n_resultados=2)
for i, doc in enumerate(resultado['documents'][0]):
    print(f"   {i+1}. {doc[:70]}...")

# Busca 3: Outra busca
print("\n3. Busca por 'programação' apenas na categoria 'programacao'")
resultado = buscar_documentos(collection, "programação", categoria="programacao", n_resultados=2)
for i, doc in enumerate(resultado['documents'][0]):
    print(f"   {i+1}. {doc[:70]}...")

SISTEMA DE BUSCA DE DOCUMENTOS
================================================================================

1. Busca geral por 'inteligência artificial'
   1. Machine Learning é um subcampo da IA que permite aos computadores apre...
   2. Vetores de alta dimensão são usados para representar dados complexos e...

2. Busca por 'dados' apenas na categoria 'ia'
   1. Machine Learning é um subcampo da IA que permite aos computadores apre...
   2. Embeddings são representações numéricas de texto que capturam signific...

3. Busca por 'programação' apenas na categoria 'programacao'
   1. Python é uma linguagem de programação extremamente versátil, usada em ...

## Conclusão

Neste notebook, você aprendeu:

✅ Como instalar e inicializar o ChromaDB  
✅ Operações CRUD (Create, Read, Update, Delete)  
✅ Busca semântica e análise de distâncias  
✅ Filtragem avançada com metadados  
✅ Persistência de dados em disco  
✅ Gerenciamento de múltiplas coleções  
✅ Construção de um sistema de busca funcional  

**Próximos passos:**
- Explore a documentação oficial: https://docs.trychroma.com
- Integre com suas próprias aplicações
- Experimente com diferentes tipos de dados e metadados
- Construa aplicações de busca semântica mais complexas

# **Construindo um RAG para notícias de cybersegurança**
Nesta seção, vamos evoluir o exemplo do ChromaDB para um RAG completo

1. Buscar noticias por RSS
2. Usar o Goose3 para extrair o texto principal das notícias
3. Quebrar os textos em chunks
4. Gerar embeddings com gemini embedding
5. Salvar os vetores no ChromaDB
6. Fazer perguntas usando o contexto recuperado
7. Gerar respostas com LLM

In [ ]:
#Instalando pacotes necessário
!pip install -q chromadb google-genai goose3 feedparser beautifulsoup4 lxml lxml_html_clean requests pandas tqdm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 15.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 6.6 MB/s eta 0:00:00
  Building wheel for langdetect (setup.py) ... done
  Building wheel for sgmllib3k (setup.py) ... done

In [ ]:
import os
import re
import time
import json
import hashlib
import textwrap
import requests
import feedparser
import pandas as pd

from tqdm.auto import tqdm
from bs4 import BeautifulSoup
from goose3 import Goose

import chromadb
from google import genai
from google.genai import types

print("Dependências instaladas e importadas !")
print("ChromaDB ", chromadb.__version__)

Dependências instaladas e importadas !
ChromaDB  1.5.9

Configuração das chaves

In [ ]:

try:
    from google.colab import userdata
    GEMINI_API_KEY = userdata.get("GEMINI_API_KEY") or os.getenv("GEMINI_API_KEY")
    OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY") or os.getenv("OPENROUTER_API_KEY")
except Exception:
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
    OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("Configure a variável GEMINI_API_KEY nos Secrets do Colab.")

if not OPENROUTER_API_KEY:
    print("Aviso: OPENROUTER_API_KEY não configurada. A geração via OpenRouter não funcionará.")

gemini_client = genai.Client(api_key=GEMINI_API_KEY)

# Modelos
GEMINI_EMBEDDING_MODEL = "gemini-embedding-2"
GEMINI_GENERATION_MODEL = "gemini-2.5-flash"

print("Gemini configurado.")
print("Modelo de embedding:", GEMINI_EMBEDDING_MODEL)
print("Modelo Gemini geração:", GEMINI_GENERATION_MODEL)

Gemini configurado.
Modelo de embedding: gemini-embedding-2
Modelo Gemini geração: gemini-2.5-flash

Listar os modelos gratuitos do OpenRouter

In [ ]:
def listar_modelos_free_openrouter(max_modelos=20):
    """
    Lista modelos do OpenRouter cujo preço de prompt e completion é 0.
    A disponibilidade pode mudar, então este método evita deixar o notebook preso a um modelo antigo.
    """
    url = "https://openrouter.ai/api/v1/models"
    resp = requests.get(url, timeout=30)
    resp.raise_for_status()
    data = resp.json()["data"]

    modelos_free = []
    for m in data:
        pricing = m.get("pricing", {})
        prompt_price = str(pricing.get("prompt", ""))
        completion_price = str(pricing.get("completion", ""))

        if prompt_price in ("0", "0.0", "0.000000") and completion_price in ("0", "0.0", "0.000000"):
            modelos_free.append({
                "id": m.get("id"),
                "name": m.get("name"),
                "context_length": m.get("context_length"),
                "prompt_price": prompt_price,
                "completion_price": completion_price,
            })

    return modelos_free[:max_modelos]

try:
    modelos_free = listar_modelos_free_openrouter()
    df_modelos_free = pd.DataFrame(modelos_free)
    display(df_modelos_free)

    OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL") or (modelos_free[0]["id"] if modelos_free else None)
    print("Modelo OpenRouter selecionado:", OPENROUTER_MODEL)
except Exception as e:
    print("Não foi possível listar modelos automaticamente:", e)
    # Ajuste manual se necessário
    OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL") or "tencent/hy3:free"
    print("Modelo fallback:", OPENROUTER_MODEL)

,id,name,context_length,prompt_price,completion_price
0,tencent/hy3:free,Tencent: Hy3 (free),262144,0,0
1,poolside/laguna-xs-2.1:free,Poolside: Laguna XS 2.1 (free),262144,0,0
2,cohere/north-mini-code:free,Cohere: North Mini Code (free),256000,0,0
3,nvidia/nemotron-3.5-content-safety:free,NVIDIA: Nemotron 3.5 Content Safety (free),128000,0,0
4,nvidia/nemotron-3-ultra-550b-a55b:free,NVIDIA: Nemotron 3 Ultra (free),1000000,0,0
5,nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:...,NVIDIA: Nemotron 3 Nano Omni (free),256000,0,0
6,poolside/laguna-xs.2:free,Poolside: Laguna XS.2 (free),262144,0,0
7,poolside/laguna-m.1:free,Poolside: Laguna M.1 (free),262144,0,0
8,google/gemma-4-26b-a4b-it:free,Google: Gemma 4 26B A4B (free),262144,0,0
9,google/gemma-4-31b-it:free,Google: Gemma 4 31B (free),262144,0,0
10,google/lyria-3-pro-preview,Google: Lyria 3 Pro Preview,1048576,0,0
11,google/lyria-3-clip-preview,Google: Lyria 3 Clip Preview,1048576,0,0
12,nvidia/nemotron-3-super-120b-a12b:free,NVIDIA: Nemotron 3 Super (free),1000000,0,0
13,openrouter/free,Free Models Router,200000,0,0
14,liquid/lfm-2.5-1.2b-thinking:free,LiquidAI: LFM2.5-1.2B-Thinking (free),32768,0,0
15,liquid/lfm-2.5-1.2b-instruct:free,LiquidAI: LFM2.5-1.2B-Instruct (free),32768,0,0
16,nvidia/nemotron-3-nano-30b-a3b:free,NVIDIA: Nemotron 3 Nano 30B A3B (free),256000,0,0
17,nvidia/nemotron-nano-12b-v2-vl:free,NVIDIA: Nemotron Nano 12B 2 VL (free),128000,0,0
18,qwen/qwen3-next-80b-a3b-instruct:free,Qwen: Qwen3 Next 80B A3B Instruct (free),262144,0,0
19,nvidia/nemotron-nano-9b-v2:free,NVIDIA: Nemotron Nano 9B V2 (free),128000,0,0

Modelo OpenRouter selecionado: tencent/hy3:free

# **Coletar notícias de Cybersegurança**

In [ ]:

NEWS_FEEDS = {
    "The Hacker News": "https://feeds.feedburner.com/TheHackersNews",
    "BleepingComputer": "https://www.bleepingcomputer.com/feed/",
    "KrebsOnSecurity": "https://krebsonsecurity.com/feed/",
    "CISA": "https://www.cisa.gov/news.xml",
    "cshub": "https://www.cshub.com/rss/articles",
}

def limpar_texto(texto):
    texto = texto or ""
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto

def fallback_extract_text(url, timeout=20):
    """
    Fallback simples caso o Goose não consiga extrair texto suficiente.
    """
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; Colab-RAG-CyberNews/1.0)"
    }
    resp = requests.get(url, headers=headers, timeout=timeout)
    resp.raise_for_status()

    soup = BeautifulSoup(resp.text, "html.parser")
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()

    paragraphs = [limpar_texto(p.get_text(" ")) for p in soup.find_all("p")]
    paragraphs = [p for p in paragraphs if len(p) > 80]
    return limpar_texto(" ".join(paragraphs))

def extrair_artigo_com_goose(url):
    """
    Extrai título, descrição e texto principal de uma notícia usando Goose3.
    Se o texto ficar muito curto, usa fallback com BeautifulSoup.
    """
    g = Goose({
        "browser_user_agent": "Mozilla/5.0 (compatible; Colab-RAG-CyberNews/1.0)",
        "use_meta_language": False,
        "target_language": "en",
    })

    article = g.extract(url=url)
    title = limpar_texto(article.title)
    meta_description = limpar_texto(article.meta_description)
    text = limpar_texto(article.cleaned_text)

    if len(text) < 500:
        try:
            text = fallback_extract_text(url)
        except Exception:
            pass

    return {
        "title": title,
        "description": meta_description,
        "text": text,
        "url": url,
    }

def coletar_noticias(feeds, max_por_fonte=3, pausa_segundos=1.0):
    """
    Lê os feeds RSS, extrai os artigos e devolve uma lista de notícias.
    """
    noticias = []

    for source, feed_url in feeds.items():
        print(f"\nFonte: {source}")
        feed = feedparser.parse(feed_url)
        entries = feed.entries[:max_por_fonte]

        for entry in tqdm(entries, desc=source):
            url = entry.get("link")
            if not url:
                continue

            try:
                artigo = extrair_artigo_com_goose(url)
                texto = artigo["text"]

                if len(texto) < 300:
                    print(f"Texto muito curto, ignorando: {url}")
                    continue

                noticias.append({
                    "source": source,
                    "feed_url": feed_url,
                    "url": url,
                    "title": artigo["title"] or limpar_texto(entry.get("title", "")),
                    "published": limpar_texto(entry.get("published", "")),
                    "description": artigo["description"] or limpar_texto(entry.get("summary", "")),
                    "text": texto,
                })

                time.sleep(pausa_segundos)

            except Exception as e:
                print(f"Erro ao processar {url}: {e}")

    return noticias

noticias = coletar_noticias(NEWS_FEEDS, max_por_fonte=2)

df_noticias = pd.DataFrame(noticias)
print("Total de notícias coletadas:", len(df_noticias))

if len(df_noticias) > 0:
    display(df_noticias[["source", "title", "published", "url"]])
else:
    print("Nenhuma notícia coletada. Teste aumentar max_por_fonte ou trocar os feeds.")

Fonte: The Hacker News

The Hacker News:   0%|          | 0/2 [00:00<?, ?it/s]

Fonte: BleepingComputer

BleepingComputer: 0it [00:00, ?it/s]

Fonte: KrebsOnSecurity

KrebsOnSecurity:   0%|          | 0/2 [00:00<?, ?it/s]

Fonte: CISA

CISA: 0it [00:00, ?it/s]

Fonte: cshub

cshub:   0%|          | 0/2 [00:00<?, ?it/s]

Total de notícias coletadas: 6

,source,title,published,url
0,The Hacker News,AI Coding Agents Found Triggering Endpoint Sec...,"Wed, 08 Jul 2026 22:32:12 +0530",https://thehackernews.com/2026/07/ai-coding-ag...
1,The Hacker News,New HalluSquatting Attack Could Trick AI Codin...,"Wed, 08 Jul 2026 20:37:24 +0530",https://thehackernews.com/2026/07/new-hallusqu...
2,KrebsOnSecurity,"Felons, Fraudsters Flog Offensive Cybersecurit...","Wed, 08 Jul 2026 12:31:39 +0000",https://krebsonsecurity.com/2026/07/felons-fra...
3,KrebsOnSecurity,"FBI Seizes NetNut Proxy Platform, Popa Botnet ...","Thu, 02 Jul 2026 19:27:33 +0000",https://krebsonsecurity.com/2026/07/fbi-seizes...
4,cshub,Cyber security governance & assurance,"Thu, 12 Jun 2025 13:36:02 +0000",https://www.cshub.com/security-strategy/articl...
5,cshub,Climate change & cybersecurity - CS Hub,"Wed, 21 May 2025 13:27:49 +0000",https://www.cshub.com/security-strategy/articl...

QUebrar as noticias em chunks, porém cada chunk deve manter os metadados originais

In [ ]:

def chunk_text(texto, chunk_size=900, overlap=150):
    """
    Chunking simples por palavras.
    - chunk_size: quantidade aproximada de palavras por chunk
    - overlap: sobreposição entre chunks
    """
    palavras = texto.split()
    chunks = []

    start = 0
    while start < len(palavras):
        end = min(start + chunk_size, len(palavras))
        chunk = " ".join(palavras[start:end]).strip()

        if chunk:
            chunks.append(chunk)

        if end == len(palavras):
            break

        start = max(0, end - overlap)

    return chunks

def gerar_chunks_noticias(noticias, chunk_size=700, overlap=120):
    documentos = []

    for noticia in noticias:
        chunks = chunk_text(noticia["text"], chunk_size=chunk_size, overlap=overlap)

        for idx, chunk in enumerate(chunks):
            base_id = f'{noticia["url"]}#{idx}'
            doc_id = hashlib.sha1(base_id.encode("utf-8")).hexdigest()

            documentos.append({
                "id": doc_id,
                "document": chunk,
                "metadata": {
                    "source": noticia["source"],
                    "title": noticia["title"],
                    "url": noticia["url"],
                    "published": noticia["published"],
                    "chunk_index": idx,
                }
            })

    return documentos

documentos_rag = gerar_chunks_noticias(noticias)

print("Total de chunks:", len(documentos_rag))
if documentos_rag:
    print("\nExemplo de chunk:")
    print("Título:", documentos_rag[0]["metadata"]["title"])
    print("Fonte:", documentos_rag[0]["metadata"]["source"])
    print("URL:", documentos_rag[0]["metadata"]["url"])
    print(textwrap.shorten(documentos_rag[0]["document"], width=700))

Total de chunks: 11

Exemplo de chunk:
Título: AI Coding Agents Found Triggering Endpoint Security Rules Built to Catch Attackers
Fonte: The Hacker News
URL: https://thehackernews.com/2026/07/ai-coding-agents-found-triggering.html
Sophos looked at a week of its own endpoint data and found that AI coding agents such as Claude Code, Cursor, and OpenAI Codex are setting off detection rules written to catch human intruders. The agents are not malicious. They just do a lot of things that, to a behavioral engine, look exactly like an attack. Decrypting browser credentials, listing what sits in Windows' credential store, pulling files down with built-in system tools, writing to the startup folder: these have long been high-signal to defenders. What has changed is who is generating it. On the machines Sophos watched, it was often a developer's AI assistant going about ordinary work. The analysis draws on seven days of [...]

Gerar embeddings e indexar no ChromaDB

In [ ]:

def embed_texts_gemini(textos, tipo="documento", output_dimensionality=768, pausa_segundos=0.1):
    """
    Gera embeddings com Gemini.
    Para o Gemini Embedding 2, usamos instruções no próprio texto para diferenciar documento e consulta.
    """
    embeddings = []

    for texto in tqdm(textos, desc=f"Gerando embeddings ({tipo})"):
        if tipo == "consulta":
            conteudo = f"Represent this question for retrieving relevant cybersecurity news chunks:\n\n{texto}"
        else:
            conteudo = f"Represent this cybersecurity news chunk for retrieval:\n\n{texto}"

        result = gemini_client.models.embed_content(
            model=GEMINI_EMBEDDING_MODEL,
            contents=conteudo,
            config=types.EmbedContentConfig(output_dimensionality=output_dimensionality),
        )

        embeddings.append(result.embeddings[0].values)
        time.sleep(pausa_segundos)

    return embeddings

# Cliente persistente: os dados ficam em /content enquanto a sessão do Colab existir.
client_cyber = chromadb.PersistentClient(path="/content/chroma_cyber_news")

collection_cyber = client_cyber.get_or_create_collection(
    name="cyber_news_gemini_768",
    metadata={
        "descricao": "RAG com notícias de cibersegurança usando Gemini embeddings",
        "hnsw:space": "cosine",
    }
)

print("Coleção:", collection_cyber.name)
print("Quantidade atual:", collection_cyber.count())

Coleção: cyber_news_gemini_768
Quantidade atual: 8

In [ ]:
# Indexação dos chunks

if not documentos_rag:
    raise ValueError("Não há documentos para indexar. Execute a coleta de notícias primeiro.")

ids = [d["id"] for d in documentos_rag]
docs = [d["document"] for d in documentos_rag]
metas = [d["metadata"] for d in documentos_rag]

embeddings_docs = embed_texts_gemini(docs, tipo="documento", output_dimensionality=768)

collection_cyber.upsert(
    ids=ids,
    documents=docs,
    metadatas=metas,
    embeddings=embeddings_docs,
)

print("Indexação concluída.")
print("Total na coleção:", collection_cyber.count())

Gerando embeddings (documento):   0%|          | 0/11 [00:00<?, ?it/s]

Indexação concluída.
Total na coleção: 11

Recuperação semântica dos dados

In [ ]:

def buscar_contextos(pergunta, n_resultados=3, fonte=None):
    query_embedding = embed_texts_gemini(
        [pergunta],
        tipo="consulta",
        output_dimensionality=768,
        pausa_segundos=0
    )[0]

    where_filter = None
    if fonte:
        where_filter = {"source": {"$eq": fonte}}

    resultados = collection_cyber.query(
        query_embeddings=[query_embedding],
        n_results=n_resultados,
        where=where_filter,
        include=["documents", "metadatas", "distances"],
    )

    contextos = []
    for doc, meta, dist in zip(
        resultados["documents"][0],
        resultados["metadatas"][0],
        resultados["distances"][0],
    ):
        contextos.append({
            "text": doc,
            "metadata": meta,
            "distance": dist,
        })

    return contextos

pergunta_teste = "Quais as novas técnicas de ataque voltada a assistentes de codificação de Inteligência Artificial (IA)?"
contextos = buscar_contextos(pergunta_teste, n_resultados=5)

for i, ctx in enumerate(contextos, start=1):
    meta = ctx["metadata"]
    print(f"\n[{i}] distância={ctx['distance']:.4f}")
    print("Fonte:", meta["source"])
    print("Título:", meta["title"])
    print("URL:", meta["url"])
    print(textwrap.shorten(ctx["text"], width=500))

Gerando embeddings (consulta):   0%|          | 0/1 [00:00<?, ?it/s]

[1] distância=0.2352
Fonte: The Hacker News
Título: New HalluSquatting Attack Could Trick AI Coding Assistants Into Installing Botnet Malware
URL: https://thehackernews.com/2026/07/new-hallusquatting-attack-could-trick.html
AI coding assistants have a habit of making things up. Ask one to fetch a popular tool, and it will sometimes hand back a real-sounding name for a project that does not exist. New research, which its authors call HalluSquatting , turns that habit into an attack: work out the fake names an AI reliably invents, register them first, and wait for the assistant to fetch your trap on a user's behalf. Anyone whose AI assistant can fetch an outside resource and then run commands with little human [...]

[2] distância=0.2626
Fonte: The Hacker News
Título: New HalluSquatting Attack Could Trick AI Coding Assistants Into Installing Botnet Malware
URL: https://thehackernews.com/2026/07/new-hallusquatting-attack-could-trick.html
learned to register fake software package names that AIs invent, a trick called "slopsquatting." In January 2026, Aikido Security's Charlie Eriksen found one such made-up npm package, react-codeshift, that AI-written instructions had already spread to 237 code projects, with agents still trying to install it daily; he registered it himself before any attacker could, so it caused no harm. The idea then jumped from packages to web addresses. Palo Alto Networks' Unit 42 recently described [...]

[3] distância=0.2866
Fonte: The Hacker News
Título: AI Coding Agents Found Triggering Endpoint Security Rules Built to Catch Attackers
URL: https://thehackernews.com/2026/07/ai-coding-agents-found-triggering.html
Sophos looked at a week of its own endpoint data and found that AI coding agents such as Claude Code, Cursor, and OpenAI Codex are setting off detection rules written to catch human intruders. The agents are not malicious. They just do a lot of things that, to a behavioral engine, look exactly like an attack. Decrypting browser credentials, listing what sits in Windows' credential store, pulling files down with built-in system tools, writing to the startup folder: these have long been [...]

[4] distância=0.3010
Fonte: The Hacker News
Título: AI Coding Agents Found Triggering Endpoint Security Rules Built to Catch Attackers
URL: https://thehackernews.com/2026/07/ai-coding-agents-found-triggering.html
agents. That is why the raw action tells you less than it once did. And it sits inside a bigger change in how intrusions look. CrowdStrike's 2026 Global Threat Report found 82 percent of 2025 detections were malware-free, with attackers moving through valid credentials and trusted tools instead of dropping files. That shift is what pushed detection toward behavior in the first place. AI agents now generate the same behavior for ordinary reasons, crowding the exact signal defenders came to [...]

[5] distância=0.3168
Fonte: cshub
Título: Climate change & cybersecurity - CS Hub
URL: https://www.cshub.com/security-strategy/articles/breaking-the-vicious-cycle-between-climate-change-cybersecurity?utm_medium=RSS
The digital world is built on a fragile physical infrastructure including multiple components like power stations, networking cables and data centers. It is highly vulnerable to climate change. Extreme weather events such as rising sea levels, flooding and hurricanes threaten the physical integrity of these components. For example, in 2012, Hurricane Sandy severed 11 out of 12 high-capacity transatlantic cables, while recent storms in the US caused widespread damage to fiber optic cables [...]

Montando o RAG: Prompt contextualizado

In [ ]:
def montar_prompt_rag(pergunta, contextos):
    blocos = []

    for i, ctx in enumerate(contextos, start=1):
        meta = ctx["metadata"]
        blocos.append(
            f"""[Fonte {i}]
Título: {meta.get("title")}
Origem: {meta.get("source")}
Data: {meta.get("published")}
URL: {meta.get("url")}
Trecho:
{ctx["text"]}
"""
        )

    contexto_formatado = "\n\n".join(blocos)

    prompt = f"""
Você é um especialista em cybersegurança e avalia noticias sobre o tema.

Responda em português do Brasil.
Use APENAS os contextos fornecidos, porém traduzindo para o português.
Cite as fontes no formato [URL 1], [URL 2] etc.
Se os contextos forem insuficientes, diga claramente que a base não traz evidência suficiente.
Não invente CVEs, datas, empresas, números ou atribuições.
Sempre traga a URL da fonte.

Pergunta:
{pergunta}

Contextos recuperados:
{contexto_formatado}

Resposta:
"""
    return prompt.strip()

prompt = montar_prompt_rag(pergunta_teste, contextos)
print(prompt[:4000])

Você é um especialista em cybersegurança e avalia noticias sobre o tema.

Responda em português do Brasil.
Use APENAS os contextos fornecidos, porém traduzindo para o português.
Cite as fontes no formato [URL 1], [URL 2] etc.
Se os contextos forem insuficientes, diga claramente que a base não traz evidência suficiente.
Não invente CVEs, datas, empresas, números ou atribuições.
Sempre traga a URL da fonte.

Pergunta:
Quais as novas técnicas de ataque voltada a assistentes de codificação de Inteligência Artificial (IA)?

Contextos recuperados:
[Fonte 1]
Título: New HalluSquatting Attack Could Trick AI Coding Assistants Into Installing Botnet Malware
Origem: The Hacker News
Data: Wed, 08 Jul 2026 20:37:24 +0530
URL: https://thehackernews.com/2026/07/new-hallusquatting-attack-could-trick.html
Trecho:
AI coding assistants have a habit of making things up. Ask one to fetch a popular tool, and it will sometimes hand back a real-sounding name for a project that does not exist. New research, which its authors call HalluSquatting , turns that habit into an attack: work out the fake names an AI reliably invents, register them first, and wait for the assistant to fetch your trap on a user's behalf. Anyone whose AI assistant can fetch an outside resource and then run commands with little human review is exposed. In tests, that path led the assistant to run attacker-supplied code on the machine. Repeat it with a popular enough resource, and one planted name can reach many machines, which is why the researchers frame it as a way to assemble a botnet. The attack chains two AI quirks. The first is a hallucination : an AI making something up and presenting it as real. The second is a prompt injection : a booby-trapped instruction that hijacks the AI, so it follows an attacker instead of the user. Here, the injection is the indirect kind, riding in on content the assistant fetches rather than anything the user types. The trap is not code that runs by itself. It works because these assistants keep a terminal among their built-in tools, so once the planted instructions take over, "install a bot" is simply something the assistant can do. What makes it practical is that the fake names are not random. In the researchers' experiments, the mistake was consistent: across different phrasings and across models from different companies, the assistant reached for the same wrong name in up to 85% of repository requests and 100% of skill installs. Those are the peak rates the authors report; the paper carries the full breakdown. They ran it against tools including Cursor, Windsurf, GitHub Copilot, Cline, Google's Gemini CLI, and the OpenClaw family of assistants, getting each to run attacker code. The test payloads were harmless placeholders, not real malware; a live one would take the same path. The research comes from Aya Spira and colleagues in Ben Nassi's group at Tel Aviv University, with Stav Cohen at Technion and Ron Bitton at Intuit. Nassi's group has done this before, building a self-spreading AI email worm and a calendar invite that hijacked Google's Gemini. The team says it told the affected vendors, model makers, and marketplace operators before going public, and held back the exact steps needed to copy the attack. Traditional botnets take work to build. They lean on weak passwords, or malware that worms from machine to machine, and they usually herd one kind of device, the way Mirai herded cameras and routers. This needs none of that. No passwords, no worming, and because the payload arrives as text the AI reads rather than a network exploit, it is not the kind of thing a firewall is watching for. The machines it lands on can run any operating system, not one uniform fleet. The AI is the delivery van here, not the cargo. The planted instructions trick it into installing an ordinary bot, and once that bot is running, the machine belongs to a botnet like any other. What is new is the combination that gets it there: a name an AI predictably invents,

RAG: Geração de respostas usando o OpenRouter

In [ ]:
import requests
from google.colab import userdata

OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")

def limpar_api_key(api_key: str) -> str:
    if not api_key:
        raise ValueError("OPENROUTER_API_KEY não encontrada. Configure a chave nos Secrets do Colab.")

    return api_key.strip().replace("\r", "").replace("\n", "")

def gerar_resposta_openrouter(pergunta, contextos, modelo="cohere/north-mini-code:free"):
    api_key = limpar_api_key(OPENROUTER_API_KEY)

    contexto_formatado = "\n\n".join(
        [
            f"Fonte {i+1}:\n{doc}"
            for i, doc in enumerate(contextos)
        ]
    )

    prompt = f"""
Você é um assistente especializado em cibersegurança.

Responda à pergunta usando apenas o contexto fornecido.
Se a resposta não estiver no contexto, diga que não há informação suficiente.

Contexto:
{contexto_formatado}

Pergunta:
{pergunta}

Resposta:
"""

    url = "https://openrouter.ai/api/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://colab.research.google.com",
        "X-Title": "RAG Cybersecurity Colab"
    }

    payload = {
        "model": modelo,
        "messages": [
            {
                "role": "system",
                "content": "Você responde perguntas usando RAG e deve evitar inventar informações. e ao final, sempre traga a URL da noticia"
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "temperature": 0.2
    }

    response = requests.post(url, headers=headers, json=payload, timeout=60)

    if response.status_code != 200:
        print("Status:", response.status_code)
        print("Resposta:", response.text)
        response.raise_for_status()

    data = response.json()
    return data["choices"][0]["message"]["content"]

In [ ]:
resposta_openrouter = gerar_resposta_openrouter(pergunta_teste, contextos)
print(resposta_openrouter)

A nova técnica de ataque descrita é **HalluSquatting**.

HalluSquatting explora duas peculiaridades dos assistentes de codificação de IA:

1. **Alucinação** – o assistente inventa um nome de projeto inexistente e o apresenta como real.
2. **Injeção de prompt (indireta)** – o assistente busca um recurso externo; se o nome inventado tiver sido registrado previamente por um atacante, o recurso buscado pode conter instruções maliciosas que o assistente executa automaticamente.

Quando um assistente tem permissão para buscar e executar código sem revisão humana (por exemplo, modos "yolo" ou "skip-permissions"), o assistente instala o código malicioso, effectively recrutando a máquina para uma botnet.

A pesquisa (por Aya Spira e colegas da Tel Aviv University, com colaborações da Technion e Intuit) demonstra a técnica em vários assistentes populares (Cursor, Windsurf, GitHub Copilot, Cline, Gemini CLI, OpenClaw, etc.) e mostra taxas de sucesso consistentemente altas (até 85% para solicitações de repositório e 100% para instalações de habilidades).

A técnica se baseia em ataques anteriores de "slopsquatting" (nomes de pacotes falsos) e "phantom squatting" (domínios inventados), mas é nova por atingir o estágio de execução de código por meio do agente de busca.

**URL da notícia:** https://thehackernews.com/2026/07/new-hallusquatting-attack-could-trick.html

Gerando com Gemini

In [ ]:
def gerar_resposta_gemini(pergunta, contextos, model=GEMINI_GENERATION_MODEL, temperature=0.2):
    prompt = montar_prompt_rag(pergunta, contextos)

    response = gemini_client.models.generate_content(
        model=model,
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=temperature,
            max_output_tokens=900,
        ),
    )

    return response.text

resposta_gemini = gerar_resposta_gemini(pergunta_teste, contextos)
print(resposta_gemini)

As novas técnicas de ataque voltadas a assistentes de codificação de Inteligência Artificial (IA) incluem:

1.  **HalluSquatting**:

In [ ]:
def perguntar_rag(
    pergunta,
    provider="openrouter",
    n_resultados=5,
    fonte=None,
    modelo_openrouter="cohere/north-mini-code:free"
):
    contextos = buscar_contextos(
        pergunta,
        n_resultados=n_resultados,
        fonte=fonte
    )

    print("Contextos recuperados:")
    for i, ctx in enumerate(contextos, start=1):
        meta = ctx["metadata"]

        print(
            f"[{i}] {meta.get('source')} | "
            f"{meta.get('title')} | "
            f"distância={ctx['distance']:.4f}"
        )
        print(meta.get("url"))
        print()

    provider = provider.lower().strip()

    if provider == "openrouter":
        resposta = gerar_resposta_openrouter(
            pergunta,
            contextos,
            modelo=modelo_openrouter
        )

    elif provider == "gemini":
        resposta = gerar_resposta_gemini(
            pergunta,
            contextos
        )

    else:
        raise ValueError("provider deve ser 'openrouter' ou 'gemini'.")

    return resposta

pergunta = "Quais incidentes ou vulnerabilidades recentes parecem mais relevantes para uma empresa monitorar?"
#print(perguntar_rag(pergunta, n_resultados=5))
print(perguntar_rag(pergunta, provider="gemini", n_resultados=5))

Gerando embeddings (consulta):   0%|          | 0/1 [00:00<?, ?it/s]

Contextos recuperados:
[1] cshub | Climate change & cybersecurity - CS Hub | distância=0.3039
https://www.cshub.com/security-strategy/articles/breaking-the-vicious-cycle-between-climate-change-cybersecurity?utm_medium=RSS

[2] cshub | Cyber security governance & assurance | distância=0.3091
https://www.cshub.com/security-strategy/articles/building-cyber-security-resilience-through-governance-assurance?utm_medium=RSS

[3] cshub | Climate change & cybersecurity - CS Hub | distância=0.3190
https://www.cshub.com/security-strategy/articles/breaking-the-vicious-cycle-between-climate-change-cybersecurity?utm_medium=RSS

[4] KrebsOnSecurity | Felons, Fraudsters Flog Offensive Cybersecurity Startup – Krebs on Security | distância=0.3271
https://krebsonsecurity.com/2026/07/felons-fraudsters-flog-offensive-cybersecurity-startup/

[5] The Hacker News | New HalluSquatting Attack Could Trick AI Coding Assistants Into Installing Botnet Malware | distância=0.3347
https://thehackernews.com/2026/07/new-hallusquatting-attack-could-trick.html

Com base nos contextos fornecidos, os incidentes ou vulnerabilidades mais relevantes para uma empresa monitorar incluem:

1.  **Vulnerabilidade da Infraestrutura Digital a Event